### ISSUE TITLE
Error During Install

### ISSUE THREAD

**Issue by satybald** [Polychart/builder#3]
While installing poly on Ubuntu 12.04 I have the following error:

URL: poly.local
Traceback (most recent call last):
  File "./install.py", line 368, in <module>
    run()
  File "./install.py", line 20, in run
    setupConfig = determineSetupConfig(installDir)
  File "./install.py", line 120, in determineSetupConfig
    result = promptSetupConfig()
  File "./install.py", line 148, in promptSetupConfig
    result['hostUrl'] = normalizeHostUrl(prompt("URL"))
  File "./install.py", line 160, in normalizeHostUrl
    return re.match(r'^([a-z]+://.+[^/])/*$', url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by satybald** [comment]
I think I got the issue. It seems that when I enter URL without http preffix it throws error as it doesn't match to Regex.

**Comment by satybald** [comment]
I think it would be nice if it would be possible to handle URL without http prefix.
